name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - hugo

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.57.2
          TARGET_REPO: mrcsxsiq/mrcsxsiq.github.io
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '-t hello-friend-ng'
          CNAME: marcosfarias.dev
